### PR TITLE
fix(MailSync/GoogleContactsWorker.cpp): enable contact sync to gracefully handle when a contact has a name but not a display name

### PR DESCRIPTION
**Pull request by ww-daniel-mora**
Intended to fix this SIGABRT but not tested or validated in any way
```
35216 [2023-03-28 11:36:59.174] [calContacts] [critical] 
***
*** Mailspring Sync 
*** An abort error (SIGABRT) occurred during program execution: 
*** system functions that detect corrupt state.
***

35216 [2023-03-28 11:36:59.184] [foreground] [info] [local-c0692241-131b] -- Succeeded. Changing status to `complete`
35216 [2023-03-28 11:36:59.198] [background] [info] Sync loop deleting unlinked messages with phase 2.
35216 [2023-03-28 11:36:59.198] [background] [info] Sync loop complete.
35216 [2023-03-28 11:36:59.198] [background] [info] Syncing folder list...
35216 [2023-03-28 11:36:59.251] [foreground] [info] syncFolderChangesViaCondstore - [Gmail]/All Mail: modseq 11009542 to 11009591, uidnext 179595 to 179595
35216 [2023-03-28 11:36:59.285] [calContacts] [critical] *** Stack trace (line numbers are approximate):
*** 0x185c21cec  pthread_kill()
*** 0x185b5a2c8  abort()
*** 0x185b59620  err()
*** in mailsync  nlohmann::basic_json const& nlohmann::basic_json::operator[](char const*) const
*** in mailsync  GoogleContactsWorker::applyJSONToContact(shared_ptr, nlohmann::basic_json const&)
*** in mailsync  GoogleContactsWorker::run()::$_0::operator()(nlohmann::basic_json) const
*** in mailsync  decltype(static_cast(fp)(static_cast(fp0))) __invoke(GoogleContactsWorker::run()::$_0&, nlohmann::basic_json&&)
*** in mailsync  GoogleContactsWorker::paginateGoogleCollection(string, string, string, function)
*** in mailsync  GoogleContactsWorker::run()
*** in mailsync  runCalContactsSyncWorker()
*** in mailsync  main::$_7::operator()() const
*** in mailsync  void* __thread_proxy(void*)
*** 0x185c1ce2c  thread_start()
```

### CODE REVIEW

**Comment by ww-daniel-mora** [comment]
Looks like this reported error https://community.getmailspring.com/t/calcontacts-gmail-sync-error/6042

**Comment by ww-daniel-mora** [comment]
Hey @bengotow  I would love your review on this one. It looks like a pretty straightforward error.

**Review by bengotow — APPROVED** [review]
This seems straightforward to me 👍  We're preparing a maintenance release, will ship this update!

**Review by bengotow — APPROVED** [review]

**Comment by ww-daniel-mora** [comment]
Thanks @bengotow. I'm trilled to get this fix in.

**Pull request merged**
