### PR TITLE
 SMTP fix - Community#1625

### PR DESCRIPTION
**Pull request by glenn2223**
Though this will fix [Comunity#1625](https://community.getmailspring.com/t/account-set-up-fails-with-smtp-error/1625), I believe it is a partial fix.

Ideally, I would like a nice subject plus a body like "This is a test email sent whilst Mailspring was setting up your account". However, my C++ knowledge is nonexistent, so I can not do this myself.

---
<details><summary>Compilation issue</summary>
I tried to run the build (that I finally managed to compile) but it failed with the error shown (all missing dll's detailed below)

image

Not sure where to find the code I need to compile the missing DLL's (as I said, I have no C++ experience 😂)
- libxml2.dll
- libcryptoMD.dll
- libtidy.dll

</details>

### CODE REVIEW

**Comment by bengotow** [comment]
Hey @glenn2223 thanks for your work on this! I think the easiest thing to do would be to copy the DLLs from your existing Mailspring install - you're totally right that they're a pain to track down...

I think if you have the app installed, there's a copy of them at `\Users\<Your User>\AppData\Local\Mailspring\app.asar.unpacked` (or close to there, I don't have my windows machine handy to check!) If you place them into the same folder your local build is running from, you'll be set!

Do you know what the subject line and content of the test message sent from Outlook are? I think you're right we should put something nice in there since people will actually see it. I can help out if you want or you can give it a shot and update the PR 👋

**Comment by glenn2223** [comment]
> I think if you have the app installed, there's a copy of them at `\Users\<Your User>\AppData\Local\Mailspring\app.asar.unpacked` (or close to there, I don't have my windows machine handy to check!)

Yeah, was close 😉. `%appdata%\..\Local\Mailspring\[version]\resources\app.asar.unpacked`

Turned out there were a few more missing. Don't know why I didn't source them from mailspring for testing 🤦‍♂️. My thinking at the time was I was doing something wrong in the compilation process.

> Do you know what the subject line and content of the test message sent from Outlook are?

Here's the test message from outlook. Overly basic IMO. The message is to me from me but with the name "Microsoft Outlook"
Basic email from outlook's SMTP test

**Comment by glenn2223** [comment]
This was my guess, probably way off the mark 😂. The code is untested as I'm now getting an MSB8036 error (as the SDK isn't installed, even though it is 🤦‍♂️)

I do have one note/question: is `mailsmtp_data_message(...)` correct or do I just `sendMessage(...)` and the previous checks become redundant (because they **_may_** be done in that method chain)? _Like I said, limited C++ experience 😁_

```CPP
void SMTPSession::checkAccount(Address * from, ErrorCode * pError)
{
    int r;
    
    loginIfNeeded(pError);
    if (* pError != ErrorNone) {
        return;
    }
    r = mailsmtp_mail(mSmtp, MCUTF8(from->mailbox()));
    saveLastResponse();
    if (r == MAILSMTP_ERROR_STREAM) {
        * pError = ErrorConnection;
        mShouldDisconnect = true;
        return;
    }
    else if (r != MAILSMTP_NO_ERROR) {
        * pError = ErrorInvalidAccount;
        return;
    }
    
    r = mailsmtp_rcpt(mSmtp, MCUTF8(from->mailbox()));
    saveLastResponse();
    if (r == MAILSMTP_ERROR_STREAM) {
        * pError = ErrorConnection;
        mShouldDisconnect = true;
        return;
    }
    else if (r != MAILSMTP_NO_ERROR) {
        * pError = ErrorInvalidRelaySMTP;
        return;
    }

    // build the MIME message
    MessageBuilder builder;
    builder.header()->setSubject(MCSTR("Mailspring SMTP Test Email"));
    builder.header()->setUserAgent(MCSTR("Mailspring"));
    builder.header()->setDate(time(0));

    Array* to = new Array();
    to->addObject(Address::addressWithDisplayName(MCSTR("Mailspring Team"), from->mailbox()));
    builder.header()->setTo(to);

    Array* replyTo = new Array();
    Address* me = Address::addressWithMailbox(from->mailbox());
    replyTo->addObject(me);

    builder.header()->setReplyTo(replyTo);
    builder.header()->setFrom(me);
    builder.setTextBody(MCSTR(
        "This is an email sent by Mailspring while we were testing your account config.\r\n\r\n"
        "As you've received it, everything must be a-ok.\r\n\r\n"
        "Kind regards,\r\nThe Mailspring Team\r\n\r\n"
        "P.S. a massive thank you for using Mailspring. We'll love you always!"
    ));

    // Save the message data / body we'll write to the sent folder
    Data* messageData = builder.data();
    
    r = mailsmtp_data_message(mSmtp, messageData->bytes(), messageData->length());
    saveLastResponse();
    if (r == MAILSMTP_ERROR_STREAM) {
        * pError = ErrorConnection;
        mShouldDisconnect = true;
        return;
    }
    else if (r != MAILSMTP_NO_ERROR) {
        * pError = ErrorInvalidRelaySMTP;
        return;
    }
    
    * pError = ErrorNone;
}
```

**Comment by glenn2223** [comment]
Realised why I got the error. I'd switched branches and lost the changes I'd made for it to compile on my PC. Sorted that and got it to compile. 

What I've done is wrong as I'm getting a `500 Syntax error, command unrecognized` error. I'll look back over it later but a little input would help 😉

**Comment by glenn2223** [comment]
Wait, figured it out! I was missing a `mailsmtp_data(...)` call.

> I do have one note/question: is `mailsmtp_data_message(...)` correct or do I just `sendMessage(...)` and the previous checks become redundant (because they **_may_** be done in that method chain)?

I think I have my answer, keep it as is. The message is being sent/received using the current (working) code

I'll push the change and, if you want to, you can tweak the wording

---

Email I've received in testing 😁
image

**Comment by glenn2223** [comment]
Hey @bengotow, have you had a chance to review this yet? Thanks

**Comment by glenn2223** [comment]
`[nudge] [nudge]` @bengotow 😉

Is this okay to merge?

**Comment by psycmos** [comment]
Mailspring 1.10.6 keep with the same issue...

**Comment by albertonoys** [comment]
> Mailspring 1.10.6 keep with the same issue...

This fix has to be merged to fix it.

**Comment by albertonoys** [comment]
@bengotow Hey Ben, could you please review this PR? I tried building my own client with this fix but I couldn't do it. I honestly can't use Thunderbird anymore 😂

**Review by bengotow — APPROVED** [review]

**Comment by bengotow** [comment]
Hey folks, sorry for the delay on this - I think this looks great. Thanks for adding a nice message! I think we can do a patch release with this and some of the other Mailspring PRs tomorrow so this doesn't have to wait longer 👋

**Pull request merged**
